[package]
name = "minbin"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A tiny (~500 LOC), zero-dependency, safe, no-std binary serializer prioritizing predictability and auditability."
repository = "https://github.com/humacss/minbin"
documentation = "https://docs.rs/minbin"
readme = "README.md"
categories = ["encoding", "no-std", "network-programming"]
keywords = ["serialization", "no-std", "binary", "encoding", "manual"]
authors = ["humacss"]

[dependencies]
# No dependencies

[dev-dependencies]
rstest = "0.26.1"
criterion = { version = "0.8", features = ["html_reports"] }

[features]
default = ["std"]
alloc = []
std = ["alloc"]

[[bench]]
name = "main"
harness = false

[[example]]
name = "macro_enum"
required-features = ["alloc"]

[[example]]
name = "macro_struct"
required-features = ["alloc"]

[[example]]
name = "manual_enum"
required-features = ["alloc"]

[[example]]
name = "manual_struct"
required-features = ["alloc"]

[package.metadata.docs.rs]
all-features = true
